cmput301-w25/project-unemployedavengers

- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- code/app/src/main/res/drawable/button_rounded_left.xml
- code/app/src/main/res/drawable/button_rounded_right.xml
- code/app/src/main/res/drawable/button_square.xml
- code/app/src/main/res/drawable/dropdown_background.xml
- code/app/src/main/res/drawable/edit_text_background.xml
- code/app/src/main/res/drawable/image_placeholder_background.xml
- code/app/src/main/res/layout/input_dialog.xml
- code/app/src/main/res/layout/mood_selector.xml
This is to check my Input Fragment and XML with Levi and Hans to coordinate. The fragment has some parts for them to review for their assigned parts
> Testing Input Fragment XML and Mood Selector XML

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/res/layout/input_dialog.xml
- code/app/src/main/res/navigation/nav_graph.xml
- Implemented add mood button that brings up input dialog using navigation
- Need to implement input
- Need to implement confirm and cancel button of input dialog
> Add mood button brings up input. Next is to implement input

- code/app/src/main/java/com/example/unemployedavengers/models/MoodEvent.java
- Creates MoodEvent model class with minimum attributes. Contains getter and setter functions.
> completed mood event model

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- code/app/src/main/res/values/colors.xml
- code/app/src/main/res/values/strings.xml
- Implemented spinner, spinner adapter, colours for spinner items, sending new mood event back, listening to receive new mood event, template for add mood function, defined some colours/spinner items, automatically store time.
> implemented sub issue 1.1.1.3

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- code/app/src/main/java/com/example/unemployedavengers/auth/Login.java
- Implemented global username and id access across classes
- Implemented database update to adding new mood event
> finished database implementation of adding mood + global access to username and id

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/arrayadapters/MoodEventArrayAdapter.java
- code/app/src/main/java/com/example/unemployedavengers/models/MoodEvent.java
- code/app/src/main/res/layout/mood_event.xml
- changed mood_event.xml design
- implemented mood event adapter, showing only mood and date. Custom colour for each mood.
- implemented sorting in dashboard (getting most recent 7 events). No need for listener since we navigate between fragments.
- connected listview with adapter
> implemented adapter for listview to show mood events. implemented sorting for most recent events. implemented fetching from firebase for moodevents

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- updated addmoodfunction to call updatemoodfunction to store id
> corrected editing logic

- code/app/src/main/java/com/example/unemployedavengers/ConfirmDeleteDialogFragment.java
- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- implemented the delete dialog that will send back info if delete is selected
- imeplemented the long click that opens delete dialog 
- need to implement listener and actual delete function
> implemented delete dialog and longpress. need to implement logic

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- created delete listener with similar logic to add listener
- created delete functions that uses id to delete
> implemented delete listener and delete function

- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- code/app/src/main/res/layout/input_dialog.xml
added maxLength to 20 characters
added 3 words limitation in reason
> Implemented editReason limitations

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- code/app/src/main/java/com/example/unemployedavengers/models/MoodEvent.java
Added reason field to mood event
changed in every part where mood event occurs
> Added reason field

- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
implemented trim on reason, trigger, situation
> implemented trim on reason, trigger, situation

- code/app/src/main/java/com/example/unemployedavengers/History.java
- implemented mood history to be able to view all mood events of a user
> History can see all mood event

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/History.java
- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- code/app/src/main/res/navigation/nav_graph.xml
- implemented history/dashboard to send source to input so it can navigate back properly
- history sees info similar to dashboard
- modified navigation graph
> implemented history seeing mood event details

- code/app/src/main/java/com/example/unemployedavengers/History.java
-implemented editing in history referring dashboard
> implemented editing in history

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/History.java
- implemented delete in history referencing dashboard
> implemented delete in history

- code/app/src/main/java/com/example/unemployedavengers/History.java
- implemented sorting of array by time
> implemented sorting

- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- code/app/src/main/java/com/example/unemployedavengers/models/MoodEvent.java
- Added RadioButton functionality 
- Updates the database
- All 02.04.01 is done
> Added Radio Button functionality and it updates the db also

- code/app/build.gradle.kts
- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- code/app/src/main/java/com/example/unemployedavengers/models/MoodEvent.java
- code/app/src/main/res/layout/input_dialog.xml
- code/gradle/libs.versions.toml
- Radio button fixed 
- Image functionality added
> Us 02.02.01.01

- code/.firebaserc
- code/app/build.gradle.kts
- code/app/src/androidTest/java/com/example/unemployedavengers/DashboardTest.java
- code/app/src/androidTest/java/com/example/unemployedavengers/FirebaseTestHelper.java
- code/app/src/main/AndroidManifest.xml
- code/app/src/main/res/xml/network_security_config.xml
- code/firebase.json
> Updated UI testing with updated imageURI

- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- Doesn't crash anymore if user doesn't select a social situation (radio button)
> Added functionality if no radio button is selected

- code/app/build.gradle.kts
- code/app/src/androidTest/java/com/example/unemployedavengers/DashboardTest.java
- code/app/src/androidTest/java/com/example/unemployedavengers/FirebaseTestHelper.java
- code/app/src/test/java/com/example/unemployedavengers/AppUnitTest.java
added Appunittest and added some comments for other parts
> Implemented AppUnitTest and added comments

- code/app/build.gradle.kts
- code/gradle/libs.versions.toml
-added dependencies to gradle files for unit testing
> added dependencies

- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- implemented 2mb limit for photo in input dialog
> implemmented 2mb limit for photo

- code/app/src/main/java/com/example/unemployedavengers/ConfirmDeleteDialogFragment.java
- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- code/app/src/main/res/layout/input_dialog.xml
- added a none option in input xml and in input. updated the logic
- ensured that buttons are theme colour
> added none option for radio button and set colours

- code/app/src/main/java/com/example/unemployedavengers/auth/Profile.java
- implemented username showing in profile
- implemented username showing in profile after username has changed
> implmemented username showing

- code/app/src/main/java/com/example/unemployedavengers/models/MoodEvent.java
- updated the model to include public status of the mood event 
- updated the model to add getting and setter function
> updated model to include public status of the mood event

- code/app/src/main/java/com/example/unemployedavengers/models/MoodEvent.java
-updated mood event constructor + typo
> Us 1.7.1.2 update model

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- code/app/src/main/res/layout/input_dialog.xml
- updated input dialog xml and java class for public status (add and edit)
- deleted some log d used for testing
> Us 01.07.01.01 input dialog update public status

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/FollowedUserMoodEvents.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/FriendsHistory.java
- code/app/src/main/res/layout/followed_user_mood_events.xml
- code/app/src/main/res/layout/friends_history.xml
- code/app/src/main/res/menu/bottom_navigation_menu.xml
- code/app/src/main/res/navigation/nav_graph.xml
Redesigned the friend system navigation by changing the Dashboard's Friends button to direct users to User Search, renaming the bottom navigation tab to "Following" to show the friends list, and added a "Friends History Mood" button that lets users view their friends' mood events, along with adding null checks to prevent crashes from destroyed fragments.
> Updated dashboard and friend section features

- code/app/src/main/java/com/example/unemployedavengers/Filter.java
- code/app/src/main/res/layout/filter.xml
- created filter dialog
- created filter class to get information and return it to parent fragment
> created the dialog and filter storing for user selection

- code/app/src/main/java/com/example/unemployedavengers/Filter.java
- code/app/src/main/java/com/example/unemployedavengers/History.java
- code/app/src/main/res/layout/filter.xml
- updated history for a listener to filter the mood events
- updated filter to correct typo
> Us 4.4.1.3 update history

- code/app/src/main/java/com/example/unemployedavengers/BaseFragment.java
- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/auth/Login.java
> Fixed crashes in BaseFragment, Dashboard, and Login

- code/app/src/main/res/layout/input_dialog.xml
- remove trigger from input xml
> remove trigger from input xml

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/arrayadapters/FollowedUserMoodEventAdapter.java
- code/app/src/main/java/com/example/unemployedavengers/auth/Login.java
- code/app/src/main/res/layout/followed_user_mood_items.xml
friends history mood alignment fixed
> Fixed alignment issues for friends mood history and removed isclicktoofast

- code/app/src/main/java/com/example/unemployedavengers/Filter.java
updata the filter let it can find recnt 7 days mood event
> Us 05.04.01.01

- code/app/src/main/java/com/example/unemployedavengers/History.java
update the history part of filter
> US 04.03.01 US 04.02.01 Update History.java

- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/auth/Login.java
- code/app/src/main/res/layout/log_in.xml
- code/app/src/main/res/navigation/nav_graph.xml
- User can successfully login without having an internet connection (from the cached data), only if they logged in before
- Also user can add mood events offline
> Login without wifi with cached data

- code/app/src/main/java/com/example/unemployedavengers/History.java
- code/app/src/main/java/com/example/unemployedavengers/arrayadapters/CommentAdapter.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/MoodDetailFragment.java
- code/app/src/main/java/com/example/unemployedavengers/implementationDAO/CommentManager.java
- Commenting works which updates the comments collection in Firebase
- Replying works and shows the expected nested comments
-Implemented indexing in the database for the IDs
> Added commenting and replying functionality with database modifications

- code/app/src/androidTest/java/com/example/unemployedavengers/UserDAOImplementTest.java
- code/app/src/main/java/com/example/unemployedavengers/DAO/IUserDAO.java
- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- code/app/src/main/java/com/example/unemployedavengers/arrayadapters/CommentAdapter.java
- code/app/src/main/java/com/example/unemployedavengers/auth/Profile.java
- code/app/src/main/java/com/example/unemployedavengers/implementationDAO/UserDAOImplement.java
- code/app/src/main/java/com/example/unemployedavengers/models/User.java
- code/app/src/main/res/layout/comment_item.xml
- code/app/src/main/res/layout/profile.xml
- Added profile avatar functionality 
- User can upload/delete their profile avatar
- Avatar also visible in the comment section of friends' mood event
> Added avatar for user

- code/app/src/main/res/layout/user_search.xml
- added a title to the user search fragment
- aligned the page
> Modified user search xml

- code/app/src/main/java/com/example/unemployedavengers/friendSection/MoodDetailFragment.java
- code/app/src/main/res/layout/mood_comments_section.xml
- code/app/src/main/res/layout/mood_detail.xml
- code/app/src/main/res/layout/reply_indicator.xml
- Replying to a comment shows a different text field now
- Adds just a replying text view instead of something complicated
> Fixed the reply comment UI

- code/app/src/main/java/com/example/unemployedavengers/Filter.java
- used the custom spinner adapter from input dialog to match the spinner here for text and colour of the mood
> updated spinner to match view

- code/app/src/main/java/com/example/unemployedavengers/History.java
- updated history to correctly show filtered mood on map.
- before the map shows all mood with emotion, now it's only filtered mood with location
> updated history to correct show filter mood on map

- code/app/src/androidTest/java/com/example/unemployedavengers/FollowFunctionalityFlowTest.java
- code/app/src/androidTest/java/com/example/unemployedavengers/FollowedUserMoodEventsTest.java
- code/app/src/androidTest/java/com/example/unemployedavengers/MoodCommentsViewTest.java
- code/app/src/androidTest/java/com/example/unemployedavengers/MoodWithPhotoTest.java
> Added Ui tests

- code/app/src/main/java/com/example/unemployedavengers/arrayadapters/FollowedUserMoodEventAdapter.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/FollowedUserMoodEvents.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/MoodDetailFragment.java
- code/app/src/main/res/navigation/nav_graph.xml
- Implemented filtering logic from history and adapted variables names for follow mood list. 
- Changed naming retrieval for filtering
- Changed navigation
> Follow filter

- code/app/src/main/java/com/example/unemployedavengers/History.java
- modified filtering for reason so that its specific word only
- before it was as long as it contained the word so if I enter "a" any text with "xxxaxx" would show up
> Added clearification of words only

- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- added picture limit byte when user upload picture
> added picture limit byte

- code/app/src/androidTest/java/com/example/unemployedavengers/FollowingFilterTest.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/MoodDetailFragment.java
added ui test and changed mood color issue while commenting
> Implemented ui test and fixed mood color issue

- code/app/src/main/java/com/example/unemployedavengers/arrayadapters/CommentAdapter.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/FollowedUserMoodEvents.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/FriendsHistory.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/MoodDetailFragment.java
- code/app/src/main/java/com/example/unemployedavengers/models/Comment.java
- code/app/src/main/res/drawable/ic_thumb_up.xml
- code/app/src/main/res/drawable/ic_thumb_up_filled.xml
- code/app/src/main/res/layout/change_password.xml
- code/app/src/main/res/layout/comment_item.xml
- code/app/src/main/res/layout/followed_user_mood_items.xml
- code/app/src/main/res/layout/friends_history.xml
- code/app/src/main/res/layout/mood_comments_section.xml
- code/app/src/main/res/layout/mood_detail.xml
- fixed onclicklisteners
- user can add/delete comment
- user can like comments
- user can reply to comments
- avatar fixes
> Resolved merge conflict with main

- code/app/src/main/java/com/example/unemployedavengers/friendSection/FollowedUserMoodEvents.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/MoodDetailFragment.java
- code/app/src/main/res/navigation/nav_graph.xml
- using the bundle send source string so mood detail fragment knows which fragment to go back to
> fixed back button on mood detail fragment to go back to parent fragment

- code/app/src/main/java/com/example/unemployedavengers/arrayadapters/FollowedUserMoodEventAdapter.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/FollowedUserMoodEvents.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/MoodDetailFragment.java
- code/app/src/main/res/layout/followed_user_mood_items.xml
- fixed loading friends' avatar in friends mood history and the comments
- fixed the faulty reply username
> avatar and reply changes

- code/app/src/main/java/com/example/unemployedavengers/Dashboard.java
- code/app/src/main/java/com/example/unemployedavengers/auth/Profile.java
- changed some toast to be more appropriately displayed or message to be more fitting
> changed some toast to be more appropriate

- README.md
add new uml and crc
Related to #257
> Add new uml

- code/app/src/androidTest/java/com/example/unemployedavengers/FilterTest.java
- code/app/src/androidTest/java/com/example/unemployedavengers/MoodWithPhotoTest.java
- code/app/src/androidTest/java/com/example/unemployedavengers/OfflineTest.java
- code/app/src/androidTest/java/com/example/unemployedavengers/ProfileTest.java
- code/app/src/main/java/com/example/unemployedavengers/MainActivity.java
- code/app/src/main/res/menu/top_navigation_menu.xml
- finished offline testing
- finished photo limit testing
- updated profile testing to fit new UI
- updated filter testing to end teardown faster
> UI testing

- code/app/src/main/java/com/example/unemployedavengers/auth/Profile.java
- code/app/src/main/java/com/example/unemployedavengers/friendSection/UserProfile.java
- code/app/src/main/res/layout/search_item.xml
- code/app/src/main/res/layout/user_profile.xml
- Added profile picture for searched user
> Added profile picture for searched users

- code/app/src/main/java/com/example/unemployedavengers/MoodFilterHelper.java
- code/app/src/test/java/com/example/unemployedavengers/MoodFilterHelperTest.java
> Added unit test for filter

- code/app/src/androidTest/java/com/example/unemployedavengers/MoodWithPhotoTest.java
- code/app/src/main/java/com/example/unemployedavengers/InputDialog.java
- fixed ui test for image selection
> ui test fix
